packages:
  - "packages/*"

catalog:
  "@types/node": ^25.9.2
  hono: ^4.12.25
  typescript: ^6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.24
  vitest: npm:@voidzero-dev/vite-plus-test@^0.1.24
  vite-plus: latest

overrides:
  vite: "catalog:"
  vitest: "catalog:"

minimumReleaseAge: 4320

allowBuilds:
  esbuild: true
